name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: gccTest
      run: gcc -o HelloWorld HelloWorld.c
 #   - name: make distcheck
 #     run: make distcheck
