name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: echoTest
      run: echo "Nu testar vi koden"
    - name: FailTest
      run: 
    - name: FailTest1
      run: 
 #   - name: make distcheck
 #     run: make distcheck
